name: Test Suite and Doc

on: [push, pull_request,  workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  # set which version it should redirect to by default
  DOC_LLVM_FEATURE: llvm15-0
  # DOC_LLVM_VERSION: '16.0'
  DOC_PATH: target/doc

jobs:
  tests:
    name: "LLVM ${{ matrix.llvm-version[0] }}: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        llvm-version:
          # - ["4.0", "4-0"]
          # - ["5.0", "5-0"]
          # - ["6.0", "6-0"]
          # - ["7.0", "7-0"]
          # - ["8.0", "8-0"]
          # - ["9.0", "9-0"]
          # - ["10.0", "10-0"]
          # - ["11.0", "11-0"]
          # - ["12.0", "12-0"]
          # - ["13.0", "13-0"]
          # - ["14.0", "14-0"]
          - ["15.0", "15-0"]
          # - ["16.0", "16-0"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ matrix.llvm-version[0] }}
      - name: Build
        run: cargo build --release --features llvm${{ matrix.llvm-version[1] }} --verbose
      - name: Run tests
        run: cargo test --release --features llvm${{ matrix.llvm-version[1] }} --verbose
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        llvm-version:
          # - ["4.0", "4-0"]
          # - ["5.0", "5-0"]
          # - ["6.0", "6-0"]
          # - ["7.0", "7-0"]
          # - ["8.0", "8-0"]
          # - ["9.0", "9-0"]
          # - ["10.0", "10-0"]
          # - ["11.0", "11-0"]
          # - ["12.0", "12-0"]
          # - ["13.0", "13-0"]
          - ["14.0", "14-0"]
          - ["15.0", "15-0"]
          # - ["16.0", "16-0"]
    # needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: docs
    - uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ matrix.llvm-version[0] }}
    - name: Install Rust Nightly
      run: |
        ls
        rustup toolchain install nightly
    - name: Build Documentation
      run: cargo +nightly doc --features llvm${{ matrix.llvm-version[1] }},nightly --verbose --target-dir  ${{ matrix.llvm-version[1]}}/
    # - uses: actions/cache@v3
    #   with:
    #     path: /tmp/doc/${{ matrix.llvm-version[1]}}/  # Note that this path is not influenced by working-directory set in defaults, for example
    #     key: the-key

    - name: add_docs
      run: |
        cp -r ${{ matrix.llvm-version[1]}}/ docs/${{ matrix.llvm-version[1]}}/
        ls
    

      